name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  # Build job
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Ruby and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full build-essential zlib1g-dev
          sudo gem install bundler
      - name: Install gems
        run: sudo bundle install
      - name: Build with Jekyll
        run: sudo bundle exec jekyll build
